iTravel/src/main/java/com/dev/itravel/models/Offer.java
package com.dev.itravel.models;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Entity
@Table(name = "offer")
@Getter @Setter @NoArgsConstructor
public class Offer {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long ID;

    private String text;
    private String tag;
    private String filename;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User author;

    public Offer(String text, String tag, User author) {
        this.text = text;
        this.tag = tag;
        this.author = author;
    }

    public String getAuthorName() {
        return author != null ? author.getUsername() : "<NONE>";
    }

}

iTravel/src/main/java/com/dev/itravel/controllers/AboutController.java
package com.dev.itravel.controllers;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class AboutController {

    @GetMapping("/about")
    public String about() {
        return "about";
    }

}

iTravel/src/main/java/com/dev/itravel/controllers/OfferController.java
package com.dev.itravel.controllers;

import com.dev.itravel.models.Offer;
import com.dev.itravel.models.User;
import com.dev.itravel.repos.OfferRepo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

@Controller
public class OfferController {

    private final OfferRepo offerRepo;

    @Value("${upload.path}")
    private String uploadPath;

    @Autowired
    public OfferController(OfferRepo offerRepo) {
        this.offerRepo = offerRepo;
    }

    @GetMapping("/offers")
    public String main(@RequestParam(required = false, defaultValue = "") String filter, Model model) {
        if (filter != null && !filter.isEmpty()) model.addAttribute("offers", offerRepo.findByTag(filter));
        else model.addAttribute("offers", offerRepo.findAll());

        model.addAttribute("filter", filter);

        return "offers";
    }

    @PostMapping("add")
    public String addOffer(@AuthenticationPrincipal User user,
                           @RequestParam String text,
                           @RequestParam String tag, Map<String, Object> model,
                           @RequestParam("file") MultipartFile file) throws IOException {
        Offer offer = new Offer(text, tag, user);

        if (file != null && !Objects.requireNonNull(file.getOriginalFilename()).isEmpty()) {
            File uploadDir = new File(uploadPath);

            if (!uploadDir.exists()) uploadDir.mkdir();

            String uuid = UUID.randomUUID().toString();
            String filename = uuid + "." + file.getOriginalFilename();
            file.transferTo(new File(uploadPath + "/" + filename));
            offer.setFilename(filename);
        }

        offerRepo.save(offer);
        model.put("offers", offerRepo.findAll());

        return "offers";
    }

}

iTravel/src/main/resources/templates/about.ftl
<#import "macros/common.ftl" as c>

<@c.page>
    <style>
        #map {
            height: 400px;  /* The height is 400 pixels */
            width: 100%;  /* The width is the width of the web page */
        }
    </style>
    <h3>My Google Maps Demo</h3>
    <!--The div element for the map -->
    <div id="map"></div>
    <script>
        // Initialize and add the map
        function initMap() {
            // The location of Uluru
            var uluru = {lat: -25.344, lng: 131.036};
            // The map, centered at Uluru
            var map = new google.maps.Map(
                document.getElementById('map'), {zoom: 4, center: uluru});
            // The marker, positioned at Uluru
            var marker = new google.maps.Marker({position: uluru, map: map});
        }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCszlVdtCBHilIFx9aiA3NJ37U0lkVUOaw&callback=initMap">
    </script>
</@c.page>

iTravel/src/main/resources/templates/index.ftl
<#import "macros/common.ftl" as c>

<@c.page>
    <h5> Hello, guest! </h5>
</@c.page>

iTravel/src/main/resources/templates/login.ftl
<#import "macros/common.ftl" as c>
<#import "macros/auth.ftl" as l>

<@c.page>
    ${message?ifExists}
    <@l.login "/login" false/>
    <a href="login/oauth2/code/177333407299-7tciosljpid69pchha33p76mctmtbbii.apps.googleusercontent.com"> Google Login </a>
    <a href="/smart-id/login"> Smart-ID login </a>
</@c.page>

iTravel/src/main/resources/templates/oauth_login.ftl
<#import "macros/common.ftl" as c>

<@c.page>

    <h3>Login with:</h3>
    <#list urls as url_k, url_v>
        <#assign var_link = "${url_v}">
        <a href="${var_link}"> Client </a>
    </#list>
</@c.page>

iTravel/src/main/resources/templates/offers.ftl
<#import "macros/common.ftl" as c>

<@c.page>
    <div class="form-row">
        <div class="form-group-col-md-5">
            <form method="get" action="/offers" class="form-inline">
                <input type="text" class="form-control" name="filter" value="${filter?ifExists}" placeholder="Search by tag">
                <button type="submit" class="btn btn-primary ml-2"> Search </button>
            </form>
        </div>
    </div>

    <a class="btn btn-primary mt-5" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Add new offer
    </a>
    <div class="collapse" id="collapseExample">
        <div class="form-group mt-3">
            <form method="post" action="/add" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="text" class="form-control" name="text" placeholder="Insert offer"/>
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" name="tag" placeholder="Insert tag">
                </div>

                <div class="custom-file">
                    <input type="file" id="customFile" name="file">
                    <label class="custom-file-label" for="customFile"> Choose file </label>
                </div>

                <input type="hidden" name="_csrf" value="${_csrf.token}"/>
                <div class="form-group mt-3">
                    <button type="submit" class="btn btn-primary"> Add </button>
                </div>
            </form>
        </div>
    </div>

    <div class="card-columns">
        <#list offers as offer>
            <div class="card my-3">
                <div class="card-img-top">
                    <#if offer.filename??>
                        <img src="/img/${offer.filename}">
                    </#if>
                </div>

                <div class="m-2">
                    <span>${offer.text}</span>
                    <i>${offer.tag}</i>
                </div>
                <div class="card-footer text-muted">
                    ${offer.authorName}
                </div>
            </div>
        <#else> No message
        </#list>
    </div>
</@c.page>

iTravel/src/main/resources/templates/profile.ftl
<#import "macros/common.ftl" as c>
<#import "macros/auth.ftl" as l>

<@c.page>
    <h5> ${username} </h5>
    ${message?ifExists}
    <div>
        <form method="post">
                <div class="form-group row"><label class="col-sm-2 col-form-label"> Email: </label>
                    <div class="col-sm-5">
                        <input type="email" class="form-control" name="email" placeholder="some@some.com" value="${email!''}"/>
                    </div>
                </div>

            <div class="form-group row"><label class="col-sm-2 col-form-label"> Password: </label>
                <div class="col-sm-5">
                    <input type="password" class="form-control" name="password" placeholder="Password"/>
                </div>
            </div>
            <input type="hidden" name="_csrf" value="${_csrf.token}"/>
            <button type="submit" class="btn btn-primary"> Save </button>
        </form>
    </div>
</@c.page>

iTravel/src/main/resources/templates/registration.ftl
<#import "macros/common.ftl" as c>
<#import "macros/auth.ftl" as l>

<@c.page>
    <div class="mb-5"><h2> Add new user </h2></div>
    ${message?ifExists}
    <@l.login "/registration" true/>
</@c.page>

iTravel/src/main/resources/templates/smartid.ftl
<#import "macros/common.ftl" as c>

<@c.page>
    <div class="container">
        <div class="header clearfix">
            <h3 class="text-muted">Veebirakenduste loomine 2018</h3>
        </div>

        <div class="jumbotron">
            <div id="smart-id-login-container">
                <h1 class="display-3" id="main-text">Logi sisse</h1>
                <form method="post">
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="countryCode" name="countryCode" placeholder="EE">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="text" class="form-control" id="nationalIdentityNumber" name="nationalIdentityNumber"
                                   aria-label="E-mail" placeholder="XXXXXXXXXXX">
                        </div>
                    </div>

                    <p><button type="submit" class="btn btn-lg btn-success">Start Smart-ID</button></p>
                </form>
            </div>
            <div id="smart-id-verification-code-container" style="display:none;">
                <h1 class="display-3" id="verification-code-text">XXXX</h1>
            </div>
        </div>

        <footer class="footer">
            <p>&copy; Tartu Ülikool 2018</p>
        </footer>

    </div>

    <script src="/webjars/jquery/jquery.min.js" defer ></script>

    <script src="../js/smartid.js" defer></script>
</@c.page>

iTravel/src/main/resources/templates/users_edit.ftl
<#import "macros/common.ftl" as c>

<@c.page>
    User editor
    <form action="/user" method="post">
        <input type="text" name="username" value="${user.username}">
        <#list roles as role>
            <div>
                <label><input type="checkbox" name="${role}" ${user.roles?seq_contains(role)?string("checked", "")}>${role}</label>
            </div>
        </#list>
        <input type="hidden" name="user_id" value="${user.ID}">
        <input type="hidden" name="_csrf" value="${_csrf.token}"/>
        <button type="submit"> Save </button>
    </form>
</@c.page>

iTravel/src/main/resources/templates/users_list.ftl
<#import "macros/common.ftl" as c>

<@c.page>
    Users list
    <table>
        <thead>
        <tr>
            <th> Name </th>
            <th> Name </th>
            <th> </th>
        </tr>
        </thead>
        <tbody>
            <#list users as user>
                <tr>
                    <td>${user.username}</td>
                    <td><#list user.roles as role>${role}<#sep>, </#list></td>
                    <td><a href="/user/${user.ID}"> edit </a></td>
                </tr>
            </#list>
        </tbody>
    </table>
</@c.page>